- hosts: master
  become: yes
  become_user: ubuntu
  tasks:
    - name: create new namespace ingress
      k8s:
        name: staging
        api_version: v1
        kind: Namespace
        state: present
    - name: Deploying ingress default backend and its services 
      become: yes
      become_user: ubuntu
      shell: kubectl create -f default-backend-deployment.yaml -f default-backend-service.yaml -n=ingress
    - name: Deploying ingress configmap 
      shell: kubectl create -f nginx-ingress-controller-config-map.yaml -n=ingress 
    - name: Deploying role for ingress
      shell: kubectl create -f nginx-ingress-controller-roles.yaml -n=ingress
    - name: Deploying ingress controller 
      shell: kubectl create -f nginx-ingress-controller-deployment.yaml -n=ingress
    - name: deploying ingress rule for nginx-stats page
      shell: kubectl create -f nginx-ingress.yaml -n=ingress
    - name: deploying ingress for app trffic
      shell: kubectl create -f app-ingress.yaml
    - name: deploying nginx ingress service controller 
      shell: kubectl create -f nginx-ingress-controller-service.yaml -n=ingress
    
